default:
	@echo "Semicon - CLI"
	@echo " make install-build-svg2png-tool"
	@echo " make build-pngs"
	
install-build-svg2png-tool:
	sudo apt-get install librsvg2-bin
	
build-pngs:
	sh scripts/build-pngs.sh
